# Generated by Django 4.2.1 on 2023-07-05 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0004_cartitem'),
    ]

    operations = [
        migrations.CreateModel(
            name='contact_us',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=100)),
                ('message', models.TextField()),
            ],
        ),
    ]
